version: '3.9'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - '3009:3009'
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - nest-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest-network

networks:
  nest-network:

volumes:
  mysql_data:
